### ISSUE TITLE
Decred 4 Year Anniversary Graphic for #DecredGlobalMeetup

### ISSUE THREAD

**Issue by Dustorf** [decred/dcrdesign#189]
Elian, Latin America Community Lead, has initiated a plan for global meetups on Thursday, February 6th, 2020, in celebration of the 4 year anniversary of the blockchain (February 8th). It would be excellent to have an image for twitter in order for various groups to promote the local events.

**Comment by 3lian** [comment]
hi dcrdesign team! 
Yes, the idea is to have an image that portraits the global nature of Decred for the #DecredGlobalMeetup, ideally I'd ask for an editable image so each community can change the local details of the meetup and translate into local languages. 
Thanks for the help!!

**Comment by 3lian** [comment]
hello, wanted to share an image that one of our contributors made for the #DecredGlobalMeetup, what you think? I'm looking for feedback because we need to get the invitation ready. What are your thoughts? If you are ok I think we could use this one, its general enough for anyone in the world using it for their local events

![IMG_4207](https://user-images.githubusercontent.com/26446555/72755799-ab815080-3bcb-11ea-889f-dfabbc42345d.png)

**Comment by Emilio-Mann** [comment]
That image looks cool, but we've used it before on the official blog.
But I see no problem in repeating

**Comment by Emilio-Mann** [comment]
One question: Why on February 6 if the birthday is on February 8?

**Comment by 3lian** [comment]
It's on [February 8th](https://explorer.dcrdata.org/block/1) but its Saturday and this day tends to be harder to organise a meetup or something as people most likely have plans on the weekend, thats why I suggested to make it on the Thursday before, which is easier for a meetup I think

**Comment by 3lian** [comment]
The good thing about it is that if we push the hashtag #DecredGlobalMeetup any country can use the image. 
I'll like to know if there is any other thoughts on the image and if no I think we should give it a go. 
This is how is looks on [eventbrite](https://www.eventbrite.com/e/decredglobalmeetup-ciudad-de-mexico-en-bitcoin-embassy-bar-tickets-90619377999).
I haven't share the event yet, waiting for more thoughts.

**Comment by linnutee** [comment]
Hey the background visual is fine, could obviously look into creating something new. Ie. a larger comp. based off the contributors portraits. 

The messaging however would be more optimal to have within the twitter templates. 
https://github.com/decred/dcrdesign/issues/17

There's also additional ones for specific events, which should contain the event details.

**Comment by 3lian** [comment]
Hi linnutee, thanks for your comments, if you recon that the timing is manageable it would be great, I think that it would be amazing to have a dedicated piece for this as there are several cities joining the campaign. I would like to share the eventbrite soon in order to have enough time for people to register. Let me know what you think.

**Comment by 3lian** [comment]
Regarding the resources you pointed, thanks a lot, I wonder if there is a repo with the editable pieces for events? I'm planning to have several events during March and I could edit an event template in AI, you know if such files are available?  

lustosa helped me several times with event pieces, not sure if he has a repo available. 

Thanks again!

**Comment by linnutee** [comment]
If you can work in .ai that would be great. Otherwise can provide just a separated version of this in xd, which is a free software. There's actually an open issue to port the templates over to xd altogether. 

Regarding the background, I could work on this early next week. Or @marcelolustosa as you're back and if interested, feel free to pitch in.

**Comment by 3lian** [comment]
I can do very basic things on .ai. Would be nice to use .xd too, I'll take a look at it, always nice to have an open source alternative.

Yes, that would be amazing, let us know to start sharing on social media. Thanks a lot, much appreciated. 

Best!

**Comment by marcelolustosa** [comment]
Looking for some feedback on this one

![dcrglobalmeetup](https://user-images.githubusercontent.com/39598223/73496705-f5babc80-4397-11ea-8e5e-8af6c47c24c0.png)

**Comment by Insaf01** [comment]
Thanks @marcelolustosa for your great work!
For Arabic the translation of the anniversary line can be like this:
الذكرى السنوية 4 لديكريد

**Comment by fguisso** [comment]
One member of community here in Brazil/Natal-RN made this one for us, can we use it, or all country need to follow one guideline?

Meetup post:
![meet-up-1q](https://user-images.githubusercontent.com/5755568/73750162-759baa80-473b-11ea-823e-a6c344b4e3aa.png)

Instagram post:
![meet-up-post](https://user-images.githubusercontent.com/5755568/73750188-7fbda900-473b-11ea-8ee9-681b22d29306.png)

**Comment by marcelolustosa** [comment]
![Artboard 1 copy 2](https://user-images.githubusercontent.com/39598223/73765030-bbb03880-4752-11ea-9129-b3003b834d40.png)
![Artboard 1 copy](https://user-images.githubusercontent.com/39598223/73765033-bbb03880-4752-11ea-81db-0afa2a77ad69.png)

@Insaf01 can you confirm the font is correct? otherwise, can you recommend a proper font?
@fguisso as long as the graphic is decent, I see no issue using a different artwork

**Comment by 3lian** [comment]
hi @marcelolustosa, awesome!! 
for Spanish it would read something like "4to Aniversario de Decred" 
thanks!

**Comment by Insaf01** [comment]
Hi @marcelolustosa, I think because of arabic use RTL for writing that all words got twisted, I've tried to fix with paint, so it should look like something in this image, can you fix it or should I just use this one
![73765033-bbb03880-4752-11ea-81db-0afa2a77ad69](https://user-images.githubusercontent.com/47435209/73827369-b5c46100-47ff-11ea-9541-bae5036f8964.png)

**Comment by marcelolustosa** [comment]
@Insaf01 thats ok!
@3lian 
![es](https://user-images.githubusercontent.com/39598223/73980917-eabfd900-490f-11ea-9c5b-46ea5854fcd6.png)
