### ISSUE TITLE
Thumbnail needed for "The Libra Effect" Panel featuring Akin.

### ISSUE THREAD

**Issue by exitus1** [decred/dcrdesign#192]
Thumbnail needed for this video:

https://www.youtube.com/watch?v=uQktZxqmAFU&feature=youtu.be

**Comment by linnutee** [comment]
Hi @exitus1 posted below. 

Regarding these talks – I think we can mostly get away with quite simple thumbnails that are just a solid crop from the video with some basic image treatment. 

In these instances for CES + Marco's talk, I noticed there wasn't any particularly good frames nor very good recording quality, combined with long titles that get slightly cut off on the titles within YT UI, so this general template makes the thumbnails slightly more impactful. 

Otherwise I would only include a specific image: 
a) When there's an existing image created as part of other visual comms (eg. key visual for twitter, etc)
b) When its content, that's part of a recurring show. ie. Decred in Depth, DA. 

![dcr - yt thumb - ces2020 akin saywer](https://user-images.githubusercontent.com/17774057/76763878-94f71000-679c-11ea-9e42-4d700e440cee.png)

https://github.com/decred/dcrdesign/issues/200
