### ISSUE TITLE
[Suggestion] Chart for proposals.decred.org

### ISSUE THREAD

**Issue by Michae2xl** [decred/dcrdesign#207]
Now that we don't have **discussion and voting**, I thought to get a new air for the Politeia page while both were 0 and/or 1.

<img width="1023" alt="poli" src="https://user-images.githubusercontent.com/44928059/80754425-0268c100-8afd-11ea-88f8-c17a17ca5bbf.png">

**Comment by victorgcramos** [comment]
Totally agree with it!

**Comment by linnutee** [comment]
Nice suggestion on improving the empty states. This makes for a great starting point to build on giving more insight for the voting. Referring to this old issue where we brought a bunch of bigger ideas to the table: https://github.com/decred/politeia/issues/678

I would look into even experimenting around with creating comparison with the approve / rejected percentages against some numbers and the treasury. Would illustrate the state even better. Any ideas from the dev both what's the limitations here and whats available as datasets that could benefit it?

**Comment by linnutee** [comment]
Prev/Specs: https://xd.adobe.com/view/10757ef8-a405-4eca-5a32-99e5cf65fec3-6644/
XD: [pi - basic proposal statistics and empty state - 050620.zip](https://github.com/decred/dcrdesign/files/4712962/pi.-.basic.proposal.statistics.and.empty.state.-.050620.zip)

Hey @Michae2xl, thought over on this a bit and attempted to make the placeholder statistic bit slightly more elaborate. 

One issue is that only using a percentage breakdown isn't too informative, since the users can already see a total numbers within the tabs above. Also need to keep in mind that the areas used are of very different size, so makes sense to have different levels of information displayed.

I've visualizing this data a bit, and without adding too much difficulty (I hope), i'd suggest adding a time factor into the play and use of stacked horizontal barcharts. This way the viewer can see a month by month birds eye view of what's been happening. 

In the proposal cards area, the breakdown can be by months, and in the smaller card on the right side, the breakdown can be by years.

Designed these as stacked horizontal barcharts – ie. https://observablehq.com/@d3/stacked-horizontal-bar-chart with styling to match the proposal indicators. 

Recommending the charts to function as following: 
- Each chart being one year, broken to 12 months and up to 12 proposals per month (visible range).
- Months read left to right and top down; the past month always as the latest and top left. (I did test with just doing top down, to simulate a timeline w/ approved and rejected diverging from the center, though this not be a practical use of space, since there's typically less than 10 proposals per month, so would be vertically too long). 

This layout should probably function well for at least another year without getting too large. I'm certain if there's any pushes towards categories per discipline or tying in the actual numbers on expenditure, we can make this quite a bit richer and look into evolving this as a separate subpage.

**Comment by Michae2xl** [comment]
I really like this concept, bars look cleaner and also by historic, it helps a lot when the people will search something, I think would be interesting a search combo box using words.. e.g when I digited "R" the system can show all = Research's proposals.
