### ISSUE TITLE
Identity: Lottie Compatible LN/DEX Icon

### ISSUE THREAD

**Issue by kyleFirethought** [decred/dcrdesign#234]
Update the LN animation to be Lottie Compatible iron out the issues with Lottie compatible DEX icon.
Upload output to Lottiefiles.

**Comment by linnutee** [comment]
Adding Privacy to the list also. I've included zip with both LN and Privacy/Incognito icons. 
[ln and privacy icons.zip](https://github.com/decred/dcrdesign/files/5543180/ln.and.privacy.icons.zip)

**Comment by linnutee** [comment]
One more to this issue. In the Mixer UI, while the mixer is running there's a visual component of these arrows which would benefit having a subtle motion to them. Ie. slowly sliding in X towards right side while fading in and out or something similar. To illustrate the process that the mixer is running and funds are being moved from unmixed to mixed account. Not this should be rather subtle and on the slow side, because there's also a the loop for the mixer running. I think we might figure out a better icon for that down the line, but its good enough for the first release.

https://gyazo.com/512f534eff5c501beecdc1348a39041e

[privacyRunningArrows.svg.zip](https://github.com/decred/dcrdesign/files/5573794/privacyRunningArrows.svg.zip)

**Comment by kyleFirethought** [comment]
**Lightning Network:**
![ln_loop](https://user-images.githubusercontent.com/7825971/100608393-3b237f80-3304-11eb-886e-f60f05f2bca4.gif)
![ln_open](https://user-images.githubusercontent.com/7825971/100613875-226b9780-330d-11eb-9e95-43c535915a3e.gif)
![ln_loop_1](https://user-images.githubusercontent.com/7825971/100608648-9d7c8000-3304-11eb-813d-fce16579c96f.gif)
**Mixer:**
![mixer_loop_var2](https://user-images.githubusercontent.com/7825971/100613651-ca349580-330c-11eb-9569-cad66c2e025e.gif)
![mixer_loop_var1](https://user-images.githubusercontent.com/7825971/100613653-cacd2c00-330c-11eb-9868-8310e685d180.gif)
![mixer_open_var1](https://user-images.githubusercontent.com/7825971/100613897-2ac3d280-330d-11eb-9898-67d8ab88bf61.gif)
**Privacy:**

**Comment by kyleFirethought** [comment]
Closed for now.
