### ISSUE TITLE
Conference Booth Concepts & Ideas

### ISSUE THREAD

**Issue by denyszayets** [decred/dcrdesign#28]
@saender @marcelolustosa @kyleFirethought @koosake @linnutee @justinsantoro
This item has been on our agenda for quite some time, and I have some great concepts and ideas I'm eager to share with you all. I'm wrapping up with few changes and will share them here asap.

**Comment by denyszayets** [comment]
Concept 1

![artboard 2 2x-100](https://user-images.githubusercontent.com/33739891/43092881-8a4e325a-8e7c-11e8-83c1-4bc010caae5f.jpg)

![artboard 2 2x-100](https://user-images.githubusercontent.com/33739891/43092891-8e30bde8-8e7c-11e8-8ea9-345fca04cb51.jpg)

**Comment by justinsantoro** [comment]
Looks great! I prefer concept 2. I like the bordering lines as well as how it's more symmetrical than concept 1. I also think the second one is more effective at catching the eye with the green details and then naturally leading it to the logo with the larger blue area. The rounded corners also help make it pop.

With the first one my eye is caught by the green in the top left and is then led down and around, never really focusing on one part.

One _tiny_ thing I noticed: 

With concept 2, the blue diamond over the blue rectangle is triggering my OCD a little bit with the top and bottom points of the diamond being so close to in line with the side of the rectangle. Maybe just push the diamonds in towards the middle a little bit more so that the outside points are inside the rectangle. I think pushing them in would also help more to bring the eye to the center.

**Comment by denyszayets** [comment]
Great observations! Thank you, and I will definitely work on them.

**Comment by saender** [comment]
Surfacing from ongoing vacation to address worriesome issues.


Lets start from the beginning with the attitude and how this is not acceptable solution. The seer point of designing this is to give focus on identity and communicate through it or simply put, having a face what is able to talk.

Output gives little to desire with the offered solution to name a few:
1. Borderline plagiarism
2. Excess work
3. Identity inconsistencies

**Borderline plagiarism**

Its a bag of unwanted thoughts at the horizon but that doesn’t tell us how we got here, so lets dig in briefly.

As a bystander of print matter in given project and having a cold nerve, this hit the cord - last week Linnutee approached me with a pico request for a solution for a booth piece, I surely agreed to co-op but mostly on the architectonical side - it was a brief brainstorm and we both were satisfied, like solving a small puzzle. Minutes later I asked him, why do You even do print design at this stage into the project? And the anwser was humoruous, as Denyz left simple designwork in the ages beyond - so I forgot it and proceeded with more pressing assignments, only later to discover his work is almost a replica we did - this hurts, even more as ones solution has morphed unwillingly into a lesser version.

Proof of this is under [dcr - environment package.zip](
https://github.com/decred/dcrdesign/files/2216290/dcr.-.environment.package.zip) 

or

https://github.com/decred/dcrdesign/releases -> Printed Matter -> Environment

or

<img width="598" alt="screen shot 2018-07-25 at 03 06 07" src="https://user-images.githubusercontent.com/29069168/43172397-c855c7ac-8fb7-11e8-838e-f8d47b50bdee.png">



**Excess work**

There was a big delay on behalf of Denyz and after awhile we moved forward with the undone work to complete it - so in all seriousness I dont understand why this GH issue is aired - deliverables are in dcr environment package mentioned above.
Regarding the background patterns to convey abstract field are already done by Jani with strong alingment with the identity and usecases, what lightly steer us to our next topic.


**Identity inconsistencies**

Only to copy and paste logo or select right color hex without constructive insight or message to communicate renders the output shallow - urging not to grow inertia in this direction.

Above concepts have a bit obscure and bulky background pattern what compete with the main focal area namely the logo, meaning it will loose depth and becomes flat.
And if we focus on the blue logo area in the last concept, then bottom round corners will break the geometrical contrast as symbol already have curves.

**Comment by denyszayets** [comment]
Hi @saender 

Plagiarism? I had my concepts created back in May/June. But I never finished with refining them. All of our work will look alike because we're working on the same brand identity. This cksplash that you just posted, I've seen it for the first time a few days ago. Unfortunately, no one bothered to ask for my feedback or opinion on it.

We already went over some details regarding this booth design, I'm sure @linnutee will fill you in.

Looking forward to hearing other contributors feedback and if there's an issue or you're not happy with this concept we can always close it and print the design you created above. **TEAM WORK!**

Thanks

**Comment by linnutee** [comment]
I will re-state the root of the problem and how Sanders feedback ties into this.
**We don’t have reasonable modular booth design, that adds up and improves DCR’s communications goals at the conferences.**

So far a number of those that’s been created, have had clear issues to them, and primarily using a pattern from the animation, that was referred from a past skyline backsplash. 
As the owner of that pattern, I’ve stated several times that it’s getting phased out and should not be used anymore in such contexts. The reason it was used in the first instance was lack of a better pattern element at that time (suitable for these kinds of space designs). Now for a while we do have one.

Now it was found out a similar booth has gone out another time, while agreement was not to and provide another solution.   I see Sander’s bigger point here in a question of “why?”. As the way this github issue was brought up seems like a reactive post to the matters brought up on Thursday, rather than something that's been worked on for a long time. 

To elaborate:
- In the previous backsplash, the logo on a solid block is a newer instance and has two very specific reasons why it is so – building visual contrast with the blockchain pattern that’s in a lineart style, and building depth by full-bleeding to the top-edge. These decisions have been specific only to the solution with the blockchain pattern here.
- However what seems to be the case here, is otherwise a similar backsplash, where the pattern has been replaced with a completely new element without any reasoning to it. 
- I agree that the cluster looks rather random, and also (besides color use) it does not add up as a part of unified visual experience with the rest of the materials used at events and DCR identity. Also as those 4 clusters are similar in size to the logo block, there’s not much contrast to it, leading to a difficulty in what to focus on. 
- This backsplash posted above by Sander though is largely based on the comments and directions I’ve already given to you, and can be a solution to be formatted and iterated on for booths – such as the common box ones.   And a matching part of the other print materials released.

In my opinion, a reasonable output here would have been a solution with the blockchain pattern (as there’s already a number of creative plays on it, including this backsplash), or at least something that makes for a unified offering with the rest of the materials within the booth and DCR identity. A solution should also be in a form of a booth, rather than just a backsplash, and address solving focal, gridding and communications issues with the previously used common box-type conference booths.   

Unless there’s reason and strong meaning behind these new elements, the big “why?” remains unanswered.   

As a follow-up action I propose to end work on this and re-brief first before continuing, to ensure the solution solves the root problems while staying aligned with the larger identity.

**Comment by denyszayets** [comment]
if that's the best route to take in your opinion, I don't have any problems with it.
