### ISSUE TITLE
Visual Style For Educational Videos

### ISSUE THREAD

**Issue by justinsantoro** [decred/dcrdesign#32]
Hello everyone. I'm opening this issue to foster discussion about the visual design of educational materials.
Some preliminary discussion has taken place [here](https://github.com/justinsantoro/video-production/issues/1).

Based on @linnutee's suggestion of 'schematic-like' I've come up with a basic icon-based visual 'scaffold' which is minimal but allows for detailed representations of technical information:

![ticket_price_algo](https://user-images.githubusercontent.com/11624082/43603989-9450612c-9662-11e8-9101-442a51e36bc0.png)

All that's left in my mind is to build up a visual design around this scaffold that is undeniably part of the Decred Identity but also set apart from other visual materials.

I understand we are still waiting for the release of the new visual guidelines and icon set, but I figured we could at least start the discussion in the meantime.

We currently have 2 scripts ready for production so once there is consensus on a design for these and the new assets are released @KyleFirethought can start animating and we can get a pipeline going to enable the regular release of this type of content.

@behindtext @raedah @saender @denyszayets @marcelolustosa @koosake

**Comment by justinsantoro** [comment]
Any thoughts or concerns regarding the 'scaffold'? And what are everyone's thoughts on light vs dark background? I'm on the fence.

**Comment by denyszayets** [comment]
I think a dark background would look better. Especially when you need to play this at the conference. not having a bright white screen is always good. Anyone else, thoughts?

**Comment by justinsantoro** [comment]
Yeah don't want to blind people. I was thinking if we went dark, it could be similar to the style of the stuff made for the pi challenge. 

![politeia-challenge](https://user-images.githubusercontent.com/11624082/44045402-674213c8-9ef6-11e8-9528-bdbdc6ec9700.jpg)

 Sort of that techie analog look, but more colorful. I'm curious what @linnutee thinks about this. 

@kyleFirethought mentioned that if we wanted it to be lighter we could use blues and white to give it a blueprint style.

**Comment by kyleFirethought** [comment]
> All that's left in my mind is to build up a visual design around this scaffold that is undeniably part of the Decred Identity but also set apart from other visual materials.

The Educational materials should be distinct from Pi materials. Moving forward Pi pieces as well as project development pieces will adopt this anologue style. 

Education materials exist to instill confidence in new users to use and engage the network. glitchy / lo-fi looks (athough cool) grind against this principle hence why I recommended inverted scheme with an orthographic / technical style.

**Comment by justinsantoro** [comment]
> Education materials exist to instil confidence in new users to use and engage the network. glitchy / lo-fi looks (although cool) grind against this principle hence why I recommended an inverted scheme with an orthographic / technical style.

Ok. makes sense. orthographic / technical it is then.

**Comment by linnutee** [comment]
Color direction is rather subjective here, ideally something derived from the context. I recon either light or dark can work. Main thing to consider is that it adds up to the rest of the series (e.g. dcr.edu, dcrassembly, roudntable etc) with a somewhat distinctive "mini-identity".

https://www.notion.so/eeter/YT-Assembly-overhaul-b03ec2f5cbb94e1ebcb6dc3971cc352b
https://www.youtube.com/playlist?list=PLaMrpvQ0yJ_z8ZtvgBqinmL74_0W7prv2
https://www.youtube.com/playlist?list=PLaMrpvQ0yJ_zjwsKYbKHcYGYwrR_ZwrBr
https://www.youtube.com/playlist?list=PLaMrpvQ0yJ_xFLGwNoDzfT6Wr0XHpyr1R

Use of a one or few complimentary colours besides grey can also help defining the style and gives a useful tool for highlighting matters.

**Comment by justinsantoro** [comment]
Here is what I came up with: https://github.com/justinsantoro/video-production/blob/7efca523439b0539b1c30b68cad6cae32406a8c6/decredPoS/decredPoS_storyboard.md

I experimented with making it look more like a technical drawing by adding borders and more lines however I felt It got too cluttered so I left it as is. I also played around with @kyleFirethought 's idea of having scenes with an inverse style for the wireframe sense but in the end I felt there weren't enough wireframe scenes to justify it. I also decided to go with yellow orange and green since they could easily be used functionally to represent yes/no etc.

**Comment by justinsantoro** [comment]
Here is the [latest design](https://github.com/raedahgroup/video-production/blob/2558909fd5863fe3f827a85e0c2b006cb47cfacd/decredUnique/decredUnique_storyboard.md) for the educational video series.

Design Goals:
1. Fit into the Decred Identity but have a mini Identity of its own.
1. Use icons and basic shapes to enable quick assembly and animating.

Using Decrediton as inspiration I have boiled down my graphics to be as minimal as possible while still conveying the ideas.

Some questionable icon usage that may need to be addressed:
- user.svg to represent 'stakehoder'
- userGroup.svg to represent 'community'
- ROI.svg to represent 'PoS'
- obtainDCR.svg to represent 'self funding'
- wallet.svg to represent 'The treasury'

Here is an [animatic](https://www.youtube.com/watch?v=DDdA66SLEFY) so you can get a feel of how it works with the voice over and basic transitions. Please be sure to read the storyboard before watching the animatic to get a full picture of the planned motion.

**Comment by linnutee** [comment]
Overall I like the visual style, seems quite consistent indeed what we got in Decrediton. As a fine detail I would consider stepping up the contrast by at least one level. Reason being in animation it’ll be harder to track these icons whilst in a still UI a lower contrast works (I did recently up it in Decrediton also). 

Scenes:
3-5 Consider iteration of cc icon to a similar coin icon w/ DCR symbol on it, more informative. 

6-9 Infographics need some work still. Slide 6 raises questions as why do the charts being from ~3 mil and follow a similar curve and why even duplicate both? I think there’s a myriad of simpler ways to visualise this notion of both being 21 mil, e.g. even just single or two progress bars that can afterwards transition into a chart. 

7-8 Same thing, it’s not very clear going the opposite direction and now using height difference to communicate difficulty difference. Current difference in the curvature is quite small and doesn’t accurately represent how harsh the reality of BTC halving is.

9 This seems a bit inaccurate. Should be 60-30-10, including 10% dev treasury. 

10-15 PoS - has a wrong icon, should be ticket. PoS/PoW is always communicated as a ticket and pickaxe comparison. 

11 I think the layout could be improved here. Regarding composition, it’s bit too static. Secondly when the legend pieces are on left and right the viewer will have to keep switching from one end of the comp. to other, may be somewhat annoying to track. 

For example (just shooting from the hip) if the chart ends up as a central piece in the scene, this can be emphasized. Instead of spreading out the PoW/PoS icons, they could pan/scale down and be positioned as sort of legend icons relating to the chart. 

Would be also preferrable using different grey tones (or just maybe this one blue) here to highlight the topic/icon currently talked about as well the chart. This blue you can sort of still work with since it only introduces one more color. But further on traffic lights + these detail combinations with different greys imo doesn’t work well. I believe i’ve covered this in a previous feedback with some examples also. 

18-23 Maybe @kyleFirethought can pitch in regarding the communication effectiveness of described animations? Not so sure these position change e.g. block falling, producing a wave and then using color as rejecting a block … but the rejected block wouldn't be in the chain. 

Taking a step back, essentially it's the notion of new block creation and PoS as a second step of verification that's being communicated here. Should consider iterating and thinking that over. In regards of the visual relations of a block + complete chain + PoS confirmations. Currently they are all levelled out – individual and equal pieces, however I'd rather look at the blockchain or specifically the latest block being the key piece + verification as (a briefly broken down) process that's affecting it. 

Don’t necessarily need to visualise the blockchain as left to right []-[]-[]-[]; but can be any kind of orderly stack that’s adding pieces one after another (depending what form makes it easier to display this process).

24-26, whilst blue and grey works to a degree, I think green/red doesn’t, esp. in details. Also find it easier to go with approving the block, this way 25-27 can be cut. This is not a common occurrence but rather makes the animation more difficult to understand. 

35-38 – also hear from Kyle, imo these have potential for some interesting transformations. E.g. users / pi symbol (circles) and roadmap being well tied together. 

28-29 interesting to see these animation. Only thing again instead of colors = how about using just icons. e.g.  https://user-images.githubusercontent.com/17774057/49388943-cd044c00-f72d-11e8-92a5-a0bea50c9d6d.png

32 Treasury should have its own icon metaphor.

43 Can promote key 3-4 key platforms for example.

**Comment by kyleFirethought** [comment]
@justinsantoro .  Any motion design requirements need to be broken down into singular issues so I can tackle these accordingly over the holiday period. In my current Pi logo issue, I will aim to get an open variant as well to be used within the video.

**Comment by justinsantoro** [comment]
As I'm sure you've all heard, I am no longer working with Raedah group. As a result I will have to turn my attention toward other projects.

This project is in need of a designer who can take what I've done so far and take it to the next level (maybe even start over), then, as Kyle mentioned above, create singular issues for the motion design requirements.

I'll be happy to help with editing all the pieces together once they are completed, if needed.

I will be updating [my fork](https://github.com/justinsantoro/video-production) of the video production repo this week. Please fork away.

**Comment by linnutee** [comment]
Closing this for the time being.
