### ISSUE TITLE
Politeia logo vertical lockups and merging to master

### ISSUE THREAD

**Issue by linnutee** [decred/dcrdesign#59]
Needs to be created, merged to master set and updated on the subpage.

**Comment by saender** [comment]
Pi logo and symbol in primary and alternative lockups, negative version has different proportions due to better optical balance.
<img width="747" alt="screen shot 2018-10-26 at 19 51 37" src="https://user-images.githubusercontent.com/29069168/47580895-c1687d00-d958-11e8-8f38-da21d25b8cbb.png">


[Politeia - Logo Package.zip](https://github.com/decred/dcrdesign/files/2520078/Politeia.-.Logo.Package.zip)
