### ISSUE TITLE
Iconset for #decrediton-dev - ticketstate and tx

### ISSUE THREAD

**Issue by kyleFirethought** [decred/dcrdesign#67]
Variants in the necessary Decrediton colour schemes for integration into application UI.

send
receive

wallet_add
wallet_subtract

tx_tax
tx
send_max

ticket_live
ticket_voted
ticket_unmined
ticket_revoked
ticket_expired
ticket_immature

error

**Comment by linnutee** [comment]
Send `#41be53` `#c4ecca`
Receive `#ed6d47` `#feb8a5`

wallet_add `#2970ff` `#E9F8FE`
instead of wallet substract use refreshWallet (decrediton launcher) `#96EBD1` `#2DD8A3`

tx_tax `#ffc84e`  `#ffe4a7`
tx – already present in nav
send_max `#2970ff`#`#70CBFF`

ticket_live  `#2970ff` `#66A9FF`
ticket_voted `#2DD8A3`  `#96EBD1`
ticket_unmined `#70CBFF` `#2970ff`
ticket_revoked `#ED6D47` `#091440`
ticket_expired `#8997A5` `#3D5873`
ticket_immature `#C4CBD2` `#596D81`

**Comment by linnutee** [comment]
Can save the stills and svg's also then.

**Comment by linnutee** [comment]
My bad, forgot I had an open issue around updating "send to self". So these two should actually be: 
sendToSelf: `#091440`  `#C4CBD2`
sendMax: `#091440`  `#C4CBD2`

<img width="495" alt="screen shot 2018-10-31 at 21 00 10" src="https://user-images.githubusercontent.com/17774057/47812076-0cff9a00-dd50-11e8-8831-c884c7cf1a24.png">

**Comment by kyleFirethought** [comment]
No worries, tickets and tx will be wrapped up tomorrow morning (only got the gif w/alpha to sort out).

The broader iconset (iconset.ai) also has a colour scheme consisting of both #091440 #C4CBD2. 

Just to clarify the whole iconset is to follow this scheme^ as packaging everything takes time.

Many thanks for sending that over*
